use crate::Error;

#[tokio::test]
async fn test_demo() -> Result<(), Error> {
    Ok(())
}